#
# simple-app.yml
#
apiVersion: kappctrl.k14s.io/v1alpha1

# We're defining an app...
kind: App
metadata:
  name: exposed-simple-app
  namespace: default
spec:

  # What service account will run this app?
  serviceAccountName: default-ns-sa

  # Where is the app coming from?
  fetch:
  - git:
      url: https://gitlab.com/drawsmcgraw/simple-kapp-deployment
      ref: origin/master

      # We have a directory, named 'app', in the root of our repo.
      # Files describing the app (i.e. pod, service) are in that directory.
      subPath: app

  # No templating yet...
  template:
  - ytt: {}
  deploy:
  - kapp: {}

